# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: django_base
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
#    command: python framework/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb_base
    env_file:
      - .env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  nginx:
    # Использование официального образа Nginx в качестве базового образа
    image: nginx
    container_name: nginx_base
    # Привязка портов хостовой машины к порту в контейнере
    ports:
      - 80:80
    # Привязка конфигурационного файла Nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      # Если у вас есть статические файлы, вы можете привязать их сюда
      # - ./static:/usr/share/nginx/html/static\

volumes:
  pgdbdata: null
